SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720
SCREEN_CENTER: tuple[int, int] = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
WORLD_WIDTH: int = 32
WORLD_HEIGHT: int = 18
TILE_SCALE: int = SCREEN_WIDTH // WORLD_WIDTH
GRAVITY_MAX: int = TILE_SCALE // 3
FPS: int = 60
